-- SCHEMA SILVER
CREATE SCHEMA IF NOT EXISTS silver;

CREATE TABLE IF NOT EXISTS silver.transactions_cards_users_mcc_fraud (
	transaction_id BIGINT NOT NULL,
	date TIMESTAMP NOT NULL,
	client_id BIGINT NOT NULL,
	card_id BIGINT,
	amount NUMERIC(10, 2) NOT NULL,
	use_chip VARCHAR(255),
	merchant_id VARCHAR(255),
	merchant_city VARCHAR(255),
	merchant_state VARCHAR(255),
	zip INTEGER,
	mcc SMALLINT NOT NULL,
	errors VARCHAR(255),
	card_brand VARCHAR(255),
	card_type VARCHAR(255),
	card_number VARCHAR(255),
	expires TIMESTAMP,
	cvv INTEGER,
	has_chip VARCHAR(255),
	num_cards_issued SMALLINT,
	credit_limit NUMERIC(10, 2),
	acct_open_date TIMESTAMP,
	year_pin_last_changed VARCHAR(255),
	card_on_dark_web VARCHAR(255),
	current_age SMALLINT,
	retirement_age SMALLINT,
	birth_year SMALLINT,
	birth_month SMALLINT,
	gender VARCHAR(255),
	address VARCHAR(255),
	latitude NUMERIC(9, 6),
	longitude NUMERIC(9, 6),
	per_capita_income NUMERIC(12, 2),
	yearly_income NUMERIC(12, 2),
	total_debt NUMERIC(12, 2),
	credit_score SMALLINT,
	num_credit_cards SMALLINT,
	mcc_description VARCHAR(255),
	is_fraud SMALLINT
);